[package]
name = "at2-web"
version = "0.1.0"
authors = ["ValÃ©rian Rousset <tharvik@users.noreply.github.com>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
yew = "0.18"

[build-dependencies]
duct = "0.13"
